### ISSUE TITLE
How to change the notification view?

### ISSUE THREAD

**Issue by demirb** [cwRichardKim/RKNotificationHub#20]
What I want to do is change the red circle to some other image, like a lightbulb.
I tried changing the hubView but it didnt work. When I tried setting the backgroundColor as an image then  the image was scaled and it only show a small part of the image.
How can I do it with this library?

**Comment by cwRichardKim** [comment]
Hmmm. unfortunately, that wasn't an intended feature.  If you're absolutely set on doing this, I would download the repository (don't use it as a cocoapod) and edit the function "setView". You'll want to change the "redCircle" object to be a UIImageView, but it might take some wrestling and you won't be able to use some of the features (animations might be weird).  Hope that helps

**Comment by demirb** [comment]
I guess I'll write something from scratch by getting inspiration from your repo. Thanks
