### ISSUE TITLE
I found a bug. It makes wrong when I change hub setting order. and I have tried to fix it. It seems that works.

### ISSUE THREAD

**Issue by yunluoxin** [cwRichardKim/RKNotificationHub#31]
- (void)moveCircleByX:(CGFloat)x Y:(CGFloat)y
{
    CGRect frame = redCircle.frame;
    frame.origin.x += x;
    frame.origin.y += y;
    
    // fix = > if we write hub.count = 999 first, and then execute -moveCircleByX:Y:, after that we execute -increment or do others, cause the method -expandToFitLargerDigits calculate the new frame base on the initialFrame, which is just changed by -moveCircleByX:Y: . It would make wrong newly frame! So we must reset, and let -expandToFitLargerDigits to recalculate.
    frame.size = initialFrame.size ;
    
    [self setCircleAtFrame:frame];
}

**Comment by cwRichardKim** [comment]
happy to take a pull request!

**Comment by yunluoxin** [comment]
fixed a small bug.
