### ISSUE TITLE
We are not able to generate baritem by hand code if want to use you lib?

### ISSUE THREAD

**Issue by songxing10000** [cwRichardKim/RKNotificationHub#33]
We are not able to generate baritem by hand code if want to use you lib?

**Comment by cwRichardKim** [comment]
i don't think i understand your question. can you please explain further?

**Comment by songxing10000** [comment]
I mean if my barItem is  generate from code use you lib not work, I see in  your demo the barItem is generate by storyboard,

**Comment by cwRichardKim** [comment]
can you show me all of the code related to this issue?

**Comment by songxing10000** [comment]
```objc
self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"fff" style:UIBarButtonItemStylePlain  target:self action:@selector(barButtonPressed)];
    barHub = [[RKNotificationHub alloc] initWithBarButtonItem: self.navigationItem.leftBarButtonItem];
    [barHub increment];
```
Before has been no effect, today re-wrote a demo, actually have effect…………

**Comment by cwRichardKim** [comment]
good to hear, i think it's likely to do with the sequence of events or some synchronicity issue!
