### ISSUE TITLE
Set the right navigation baritem and red point dot does not display

### ISSUE THREAD

**Issue by luluAngle** [cwRichardKim/RKNotificationHub#34]
use you demo code,my app display red point.code is 
 barHub = [[RKNotificationHub alloc] initWithBarButtonItem: self.barButtonItem];
    barHub.count = 6;
    [barHub showCount];

**Comment by cwRichardKim** [comment]
this is likely to do with how UINavigationBar boxes the buttons. it's very difficult to work with custom views in UINavigationBar, so unfortunately it's out of scope of this project. i'm happy to accept a pull request if a solution is found
