### ISSUE TITLE
outer ring had noise when set border

### ISSUE THREAD

**Issue by f40507777** [cwRichardKim/RKNotificationHub#35]
when I set border color and width
the outer ring had thin circle color border

    [hub setCircleColor:[UIColor brownColor] labelColor:[UIColor greenColor]];
    [hub setCircleBorderColor:[UIColor yellowColor] borderWidth:2.0];

![simulator screen shot - iphone 7 - 2017-09-15 at 11 39 35](https://user-images.githubusercontent.com/5353541/30465999-60b0252a-9a0d-11e7-83ce-cba8ffbb2b72.png)

**Comment by cwRichardKim** [comment]
hey, unfortunately i didn't write the border code, it's just a standard CALayer property.  have you tried running it on a device? maybe it's just how your simulator screen renders it.  I'm going to close this because it's not an issue with this library
