### ISSUE TITLE
New CocoaPod for updated master branch?

### ISSUE THREAD

**Issue by zachlucas** [cwRichardKim/RKNotificationHub#36]
Could we get an updated pod version push for what's on master?

**Comment by cwRichardKim** [comment]
I believe the only thing that's outside of the current release is markdown changes on the readme. is there something in particular that you're looking for?

**Comment by cwRichardKim** [comment]
@zachlucas feel free to respond, but I'm going to close this issue for now since I don't see any reason to create a new release just for a small readme change

**Comment by zachlucas** [comment]
@cwRichardKim I'm using the `setCircleBorderColor:borderWidth` method, that's on master but not on latest version it seems: 
https://github.com/cwRichardKim/RKNotificationHub/compare/2.0.4...master

**Comment by cwRichardKim** [comment]
oh yea you're totally right, I was looking at the wrong year lol.  I'll fix this later today when I get off work, thanks for pointing this out

**Comment by cwRichardKim** [comment]
@zachlucas done, let me know if there are any issues 👍
