### ISSUE TITLE
Badge disapeare 

### ISSUE THREAD

**Issue by petaren** [cwRichardKim/RKNotificationHub#6]
I put the NotificationHub on a UIImageView in a UITableViewCell. When I select that tableviewcell and animate to the detailViewController then the badge disappears and only the number label is visible. 
![img_0010](https://cloud.githubusercontent.com/assets/3486895/6038051/120787ea-ac5a-11e4-9775-c93c35c3432a.PNG)
![img_0011](https://cloud.githubusercontent.com/assets/3486895/6038052/12299d62-ac5a-11e4-9e13-4f294a0389e2.PNG)

**Comment by petaren** [comment]
So I've done some research and found the cause. This is caused due to UITableViewCell setting all its subviews .backgroundColor to [UIColor whiteColor] when it is selected. This makes the red circle disappear.

**Comment by petaren** [comment]
Created a pull request with a possible solution to this issue.

**Comment by marcelosalloum** [comment]
[LIKE]
